paths:
  textinfo: "Dataset/RawDataset/concathumantext.json"

newpaths:
  HumanMBotData: "Dataset/ExperimentDataset/HumanMBotData.json"
  HumanSummerizeText: "Dataset/ExperimentDataset/humantextsummary.json"
  HumanHistricalInfo: "Dataset/ExperimentDataset/HumanHistricalInfo.json"
  MBotHistricalInfo: "Dataset/ExperimentDataset/MBotHistricalInfo.json"

Parameters:
  ordernum: 1
  alpha: 0.1
  gamma: 0.5
  beta: 0.1
  botpostsratio: 0.2
  BeginNodeNumber: 2

disinfopaths:
  Business: "Experiment/Dataset/Disinformation/BusinessDisinformation.yaml"
  Education: "Experiment/Dataset/Disinformation/EducationDisinformation.yaml"
  Entertainment: "Experiment/Dataset/Disinformation/EntertainmentDisinformation.yaml"
  Politics: "Experiment/Dataset/Disinformation/PoliticsDisinformation.yaml"
  Sports: "Experiment/Dataset/Disinformation/SportsDisinformation.yaml"
  Technology: "Experiment/Dataset/Disinformation/TechnologyDisinformation.yaml"
  Prompt: "Experiment/Prompt/F_j.yaml"
  JudgeStance: "Experiment/Prompt/judgestance.yaml"
  TrustPrompt: "Experiment/Prompt/believeaction.yaml"
  UnbelievePrompt: "Experiment/Prompt/unbelieveaction.yaml"
  BotactionPrompt: "Experiment/Prompt/botaction.yaml"
  InformationPlausibility: "Experiment/Prompt/informationplausibility.yaml"

log:
  Disseminate_log_file: "Experiment/log/Disseminate_log.txt"

DisinfoClaim:
  Business: "Elon Musk unveils a $100 Tesla tablet that will revolutionize the technological world."
  Education: "People can get student debt 'erased' by filing Family Educational Rights and Privacy Act complaints because the Department of Government Efficiency accessed federal student loan databases."
  Entertainment: "Country singer Chris Stapleton filed an official objection after Beyoncé's 'Cowboy Carter' won the 2025 Grammy award for best country album."
  Politics: "The U.S. House Select Committee that investigated the Jan. 6, 2021, attack on the U.S. Capitol 'deleted and destroyed all of the information that they collected over two years.'"
  Sports: "Michael Jordan said that 'any athlete who kneels for our national anthem should lose their medal'"
  Technology: "There will be more plastic than fish in the world's oceans by 2050"