LBotRatio:
  EntertainmentLBotRatio: 0.05
  EducationLBotRatio: 0.05
  BusinessLBotRatio: 0.05
  SportsLBotRatio: 0.05
  PoliticsLBotRatio: 0.05
  TechnologyLBotRatio: 0.05


MBotRatio:
  EntertainmentBotRatio: 0.15
  EducationBotRatio: 0.15
  BusinessBotRatio: 0.15
  SportsBotRatio: 0.15
  PoliticsBotRatio: 0.15
  TechnologyBotRatio: 0.15


LBotCorrectionTime:
  EarlyCorrectionTime: 12
  MiddleCorrectionTime: 36
  LateCorrectionTime: 48


parameters:
  m: 5
  m1: 4
  MaxActivationTimes: 18
  numbers_1: 1
  numbers_2: 25
  weights_1: 0.8
  weights_2: 0.2
  
MBotLBotPaths:
  MBotLBotEdgeIndex: "Dataset/CorrectDataset/NetworkDataset/EdgeIndex/"


paths:
  SampleDataset: "Dataset/NetworkDataset/SampleHumanData/sampled_human_attribute_data.json"
  MBotHumanDataset: "Dataset/NetworkDataset/MBotHumanDataset/HumanMBotData.json"
  ConcatHumanMBots: "Dataset/NetworkDataset/MBotHumanDataset/concat_human_mbots.json"

log:
  construct_network: "CorrectExperiment/GenerateMLNetwork/Log/construct_ML_network.log"

newpaths:
  MBotDataset: "Dataset/NetworkDataset/MBotDataset/MBotDataset.json"
  LBotDataset: "Dataset/NetworkDataset/LBotDataset/LBotDataset.json"
  ConcatHumanMBotLBot: "Dataset/NetworkDataset/ConcatHumanMBotLBot/concat_human_mbot_lbot.json"