paths:
  textinfo: "Dataset/RawDataset/concathumantext.json"
  sharenumfile: "Dataset/SimulateDataset/share_num.json"
  human_ids_Education: "Dataset/NetworkDataset/CommunityID/Education_community_human.npy"
  mbot_ids_Education: "Dataset/NetworkDataset/CommunityID/Education_community_mbot.npy"
  lbot_ids_Education: "Dataset/NetworkDataset/CommunityID/Education_community_lbot.npy"
  human_ids_Entertainment: "Dataset/NetworkDataset/CommunityID/Entertainment_community_human.npy"
  mbot_ids_Entertainment: "Dataset/NetworkDataset/CommunityID/Entertainment_community_mbot.npy"
  lbot_ids_Entertainment: "Dataset/NetworkDataset/CommunityID/Entertainment_community_lbot.npy"  
  human_ids_Sports: "Dataset/NetworkDataset/CommunityID/Sports_community_human.npy"
  mbot_ids_Sports: "Dataset/NetworkDataset/CommunityID/Sports_community_mbot.npy"
  lbot_ids_Sports: "Dataset/NetworkDataset/CommunityID/Sports_community_lbot.npy"
  human_ids_Politics: "Dataset/NetworkDataset/CommunityID/Politics_community_human.npy"
  mbot_ids_Politics: "Dataset/NetworkDataset/CommunityID/Politics_community_mbot.npy"
  lbot_ids_Politics: "Dataset/NetworkDataset/CommunityID/Politics_community_lbot.npy"
  human_ids_Technology: "Dataset/NetworkDataset/CommunityID/Technology_community_human.npy"
  mbot_ids_Technology: "Dataset/NetworkDataset/CommunityID/Technology_community_mbot.npy"
  lbot_ids_Technology: "Dataset/NetworkDataset/CommunityID/Technology_community_lbot.npy"
  human_ids_Business: "Dataset/NetworkDataset/CommunityID/Business_community_human.npy"
  mbot_ids_Business: "Dataset/NetworkDataset/CommunityID/Business_community_mbot.npy"
  lbot_ids_Business: "Dataset/NetworkDataset/CommunityID/Business_community_lbot.npy"
  edge_index: "Dataset/NetworkDataset/EdgeIndex/mbot_human_lbot_edge_index.npy"
  edge_index_Education: "Dataset/NetworkDataset/EdgeIndex/mbot_human_lbot_edge_index_community_Education.npy"
  edge_index_Business: "Dataset/NetworkDataset/EdgeIndex/mbot_human_lbot_edge_index_community_Business.npy"
  edge_index_Entertainment: "Dataset/NetworkDataset/EdgeIndex/mbot_human_lbot_edge_index_community_Entertainment.npy"
  edge_index_Sports: "Dataset/NetworkDataset/EdgeIndex/mbot_human_lbot_edge_index_community_Sports.npy"
  edge_index_Politics: "Dataset/NetworkDataset/EdgeIndex/mbot_human_lbot_edge_index_community_Politics.npy"
  edge_index_Technology: "Dataset/NetworkDataset/EdgeIndex/mbot_human_lbot_edge_index_community_Technology.npy"
  HumanMBotLBotData: "Dataset/NetworkDataset/ConcatHumanMBotLBot/concat_human_mbot_lbot_DT.json"
  HumanSummerizeText: "Dataset/SimulateDataset/humantextsummary.json"
  HumanMBotLBotDataBusiness: "Dataset/NetworkDataset/ConcatHumanMBotLBot/concat_human_mbot_lbot_business.json"
  HumanMBotLBotDataEntertainment: "Dataset/NetworkDataset/ConcatHumanMBotLBot/concat_human_mbot_lbot_entertainment.json"
  HumanMBotLBotDataSports: "Dataset/NetworkDataset/ConcatHumanMBotLBot/concat_human_mbot_lbot_sports.json"
  HumanMBotLBotDataEducation: "Dataset/NetworkDataset/ConcatHumanMBotLBot/concat_human_mbot_lbot_education.json"
  HumanMBotLBotDataPolitics: "Dataset/NetworkDataset/ConcatHumanMBotLBot/concat_human_mbot_lbot_politics.json"
  HumanMBotLBotDataTechnology: "Dataset/NetworkDataset/ConcatHumanMBotLBot/concat_human_mbot_lbot_technology.json"

newpaths:
  BusinessSimulationResult: "Dataset/SimulateDataset/SimulateResult/BusinessSimulationResult_narrative_early.yaml"
  SportsSimulationResult: "Dataset/SimulateDataset/SimulateResult/SportsSimulationResult_narrative_early.yaml"
  TechnologySimulationResult: "Dataset/SimulateDataset/SimulateResult/TechnologySimulationResult_narrative_early.yaml"
  EntertainmentSimulationResult: "Dataset/SimulateDataset/SimulateResult/EntertainmentSimulationResult_narrative_early.yaml"
  EducationSimulationResult: "Dataset/SimulateDataset/SimulateResult/EducationSimulationResult_narrative_early.yaml"
  PoliticsSimulationResult: "Dataset/SimulateDataset/SimulateResult/PoliticsSimulationResult_narrative_early.yaml"

History:
  HumanHistricalInfoEntertainment: "Dataset/SimulateDataset/History/Entertainment/HumanHistricalInfosEntertainment_narrative_early.json"
  MBotHistricalInfoEntertainment: "Dataset/SimulateDataset/History/Entertainment/MBotHistricalInfosEntertainment_narrative_early.json"
  LBotHistricalInfoEntertainment: "Dataset/SimulateDataset/History/Entertainment/LBotHistricalInfosEntertainment_narrative_early.json"
  HumanHistricalInfoSports: "Dataset/SimulateDataset/History/Sports/HumanHistricalInfosSports_narrative_early.json"
  MBotHistricalInfoSports: "Dataset/SimulateDataset/History/Sports/MBotHistricalInfosSports_narrative_early.json"
  LBotHistricalInfoSports: "Dataset/SimulateDataset/History/Sports/LBotHistricalInfosSports_narrative_early.json"
  HumanHistricalInfoEducation: "Dataset/SimulateDataset/History/Education/HumanHistricalInfosEducation_narrative_early.json"
  MBotHistricalInfoEducation: "Dataset/SimulateDataset/History/Education/MBotHistricalInfosEducation_narrative_early.json"
  LBotHistricalInfoEducation: "Dataset/SimulateDataset/History/Education/LBotHistricalInfosEducation_narrative_early.json"
  HumanHistricalInfoPolitics: "Dataset/SimulateDataset/History/Politics/HumanHistricalInfosPolitics_narrative_early.json"
  MBotHistricalInfoPolitics: "Dataset/SimulateDataset/History/Politics/MBotHistricalInfosPolitics_narrative_early.json"
  LBotHistricalInfoPolitics: "Dataset/SimulateDataset/History/Politics/LBotHistricalInfosPolitics_narrative_early.json"
  HumanHistricalInfoTechnology: "Dataset/SimulateDataset/History/Technology/HumanHistricalInfosTechnology_narrative_early.json"
  MBotHistricalInfoTechnology: "Dataset/SimulateDataset/History/Technology/MBotHistricalInfosTechnology_narrative_early.json"
  LBotHistricalInfoTechnology: "Dataset/SimulateDataset/History/Technology/LBotHistricalInfosTechnology_narrative_early.json"
  HumanHistricalInfoBusiness: "Dataset/SimulateDataset/History/Business/HumanHistricalInfosBusiness_narrative_early.json"
  MBotHistricalInfoBusiness: "Dataset/SimulateDataset/History/Business/MBotHistricalInfosBusiness_narrative_early.json"
  LBotHistricalInfoBusiness: "Dataset/SimulateDataset/History/Business/LBotHistricalInfosBusiness_narrative_early.json"

Parameters:
  ordernum: 1
  gamma: 0.5
  beta: 1
  botpostsratio: 0.2
  BeginNodeNumber: 5
  delta: 1
  xi: 0.1
  n0: 5
  correctstrategy: "FactBased"
  inferenece_time: "early_correction_activation_time"

disinfopaths:
  Business: "Dataset/Disinformation/BusinessDisinformation.yaml"
  Education: "Dataset/Disinformation/EducationDisinformation.yaml"
  Entertainment: "Dataset/Disinformation/EntertainmentDisinformation.yaml"
  Politics: "Dataset/Disinformation/PoliticsDisinformation.yaml"
  Sports: "Dataset/Disinformation/SportsDisinformation.yaml"
  Technology: "Dataset/Disinformation/TechnologyDisinformation.yaml"

promptpaths:
  CalculateInfoScore: "SimulateExperiment/Prompt/F_j.yaml"
  JudgeStance: "SimulateExperiment/Prompt/judgestance.yaml"
  TrustPrompt: "SimulateExperiment/Prompt/believeaction.yaml"
  UnbelievePrompt: "SimulateExperiment/Prompt/unbelieveaction.yaml"
  BotactionPrompt: "SimulateExperiment/Prompt/botaction.yaml"
  InformationPlausibility: "SimulateExperiment/Prompt/informationplausibility.yaml"
  RewriteDisinformation: "SimulateExperiment/Prompt/rewrite.yaml"
  RewriteCorrectInformation: "SimulateExperiment/Prompt/rewrite_corrective_info.yaml"

log:
  Disseminate_log_file: "CorrectExperiment/Simulate/log/Disseminate_log_narrative_early.txt"

DisinfoClaim:
  Business: "Tariff policy is a tax reduction for the American people."
  Education: "People can get student debt 'erased' by filing Family Educational Rights and Privacy Act complaints because the Department of Government Efficiency accessed federal student loan databases."
  Entertainment: "Country singer Chris Stapleton filed an official objection after Beyoncé's 'Cowboy Carter' won the 2025 Grammy award for best country album."
  Politics: "The U.S. House Select Committee that investigated the Jan. 6, 2021, attack on the U.S. Capitol 'deleted and destroyed all of the information that they collected over two years.'"
  Sports: "Michael Jordan said that 'any athlete who kneels for our national anthem should lose their medal'"
  Technology: "There will be more plastic than fish in the world's oceans by 2050"